version: "2"

run:
  tests: true
  build-tags:
    - golangci
  allow-parallel-runners: true

linters:
  # Which dirs to skip. Issues from them won't be reported.
  exclusions:
    paths:
      - .github
  # Enable all linters. Conf settings may follow.
  default: all

  disable:
  # Disabled because of testing private functions
  - testpackage
  # We allow global variable for testing purposes
  - gochecknoglobals
  # Disabled due to the use of external packages
  - depguard
  # ========================================
  # Disable deprecated/abandoned linters
  # ========================================
  # Disabled due to wsl_v5
  - wsl
